### ISSUE TITLE
Crash : double free pointer 

### ISSUE THREAD

**Issue by bilsou** [kittinunf/Cookpit#15]

**Comment by kittinunf** [comment]
Hmm, interesting. I am not aware of that issue at all. Can you tell me how to replicate that?

**Comment by bilsou** [comment]
I haven't done anything really, just tried to start it after cloning the repo. 
One thing though is that I had to use this `carthage update --platform iOS --no-use-binaries` as otherwise it was using binaries with Swift 3.0.1 compiler which I am not using. (using Swift 3.0).

**Comment by kittinunf** [comment]
Sorry if my question was not clear. I mean that did you experience the crash on the first run?

I have it run perfectly with iOS and Android on my machine;

![screen shot 2016-12-21 at 9 39 45 pm](https://cloud.githubusercontent.com/assets/4669517/21389650/1bc66cd6-c7c6-11e6-8895-1ad970d080e8.png)

What I did to simulate your situation is to clean everything by

`git clean -fxd`
`make clean`
`make all`

### iOS
Go into ios folder

`carthage update --platform iOS`

Open Cookpit.xcworkspace

Run the app.

### Android
Use Android studio to import project.

Sync project then run the app.

The only thing that we did differently is to update carthage. But I don't think it has anything to do with the free pointer problem though.

**Comment by bilsou** [comment]
I updated my Swift compiler so I don't have to update carthage or use a different command and did the exact other steps you mentioned for iOS (not trying Android for now) and ended up with the same issue: 

<img width="1437" alt="screen shot 2016-12-21 at 14 19 20" src="https://cloud.githubusercontent.com/assets/10742657/21390704/8ec30b38-c788-11e6-9087-a7d31e7785f4.png">

Have no clue why it would do that to be honest

**Comment by kittinunf** [comment]
Wow ... I think I should know if I can replicate it. However, I dunno how to run into that situation. I would love to understand the problem. Is there anything with Swift compiler? What Xcode version do you have?

**Comment by bilsou** [comment]
```
Xcode 8.2.1
Build version 8C1002
```

```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

If it comes to that I can downgrade and install the Xcode and Swift version you have

**Comment by kittinunf** [comment]
Oh wow.

`xcrun swift -version` is 

```
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```

And I am also using Xcode 8.2.1 as well.

**Comment by bilsou** [comment]
I was suspecting it from your screenshots and now have the confirmation. 
It works only if using the simulator and not on a real device. 
I don't know why though

**Comment by kittinunf** [comment]
I just got back from the holidays. I will look into issue tonight. Thanks for reporting this btw.

**Comment by kittinunf** [comment]
I made a PR #16 to fix this issue. I am able to run on my iPhone device now. Could you please try and see whether it works for you?

**Comment by bilsou** [comment]
Just tried, works as expected on my iphone 6. 
Thanks a lot for both the fix and the app itself, really valuable for cross platform development in C++ and djinni.

**Comment by kittinunf** [comment]
Hey thanks for reporting this. Without you, I would not have known that there is an issue. Also just to let you know that this is totally open and you could do anything you want with it.

**Comment by bilsou** [comment]
It helped me a lot to get started with djinni as well as looking how to use a "C++ redux" across all platforms. 
Btw do you know how to add the `non nullable pointers` option to run_djinni, I tried adding     
```
--cpp-nn-header "\"nn_header.hpp\"" \
--cpp-nn-type "nn_type" \
--cpp-nn-check-expression "nn_check_expression" \
```
but end up having compiling issues with the header not found, I have no clue where to add this header to the build system

**Comment by kittinunf** [comment]
I am not sure because I didn't use `nn` myself. Is the `nn_header.hpp` in the location that source code  can be referenced to?

**Comment by bilsou** [comment]
I initially thought it would be shipped out with the extension-libs but it was not. So I took it out from here directly [https://github.com/dropbox/nn](url). As it is a header only I just put it at the `vendors` root folder but it can't find it during the compilation phase.

**Comment by kittinunf** [comment]
Have you add it into the gyp file so that the source can locate the header? Something pretty much like what I did here. https://github.com/kittinunf/Cookpit/blob/master/cookpit.gyp#L48-L52

**Comment by bilsou** [comment]
Yes I did add it here 

`'include_dirs': [
        'vendors/flowcpp/include',
        'vendors/json11',
        'vendors/curl/<(OS)/include',
        'vendors/lmdb/libraries/liblmdb',
        'vendors/lmdbxx',
        'vendors/',
      ],`

As it is a header only I thought that should be enough

**Comment by bilsou** [comment]
I managed to get the nn header being found by specifying the full path via 
`--cpp-nn-header "\"$base_dir/vendors/nn/nn_header.hpp\""` (I created a nn subfolder in vendors)
but to make djinni use the non nullable pointers by default when generating the files, there is the 
`--cpp-nn-type` option to specify and so far no luck. I tried `--cpp-nn-type "dropbox::oxygen::nn"` but fails when compiling. 
Anyway if you have some time that would be a nice thing to add to your flickr app as a good example of using non nullable objects throughout the platforms (Kotlin/Java and Swift/ObjC do actually support them)

**Comment by bilsou** [comment]
Sorry for not getting back to you earlier, I managed to use the `nn` library. It was actually an issue on the `dropox/nn` repo itself, it has been fixed after I filed a bug.

By the way, flowcpp is not so straightforward to use, trying to implement a sign up/ log in process and having some issues for sure.

**Comment by kittinunf** [comment]
Can you be more specific on which part is not good? I really open for suggestions. I used it with my previous company and it worked quite well. 

If it's okay you could show me you code, and I will go there to take a look too!

**Comment by bilsou** [comment]
I might have misspoken, I meant the whole FRP (functional reactive paradigm) is really not that easy to get. As a former WPF/UWP developer, I'm quite experienced with MVVM but the FRP has a really high learning curve at the beginning for sure, even though I can definitely see the advantages it has. Your Flickr app is great at showing how to use Djinni in a cross platform way but with both RxSwift and flowcpp glued together can make it somehow hard to get.
